version: '3.8'

services:
  flask-app:
    container_name: flask_app
    build: .
    ports:
      - "8080:8080"
    environment:
      - FLASK_ENV=production
      - PORT=8080
    volumes:
      - .:/app
    restart: unless-stopped